---
title: "GOVT6139</br>Research design"
subtitle: "Week 07</br>The Introduction & The Purpose Statement"
author: "Francesco Bailo"
institute: "The University of Sydney"
date: "Semester 1, 2024 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    css: ["default", "assets/sydney-fonts.css", "assets/sydney.css"]
    self_contained: false # if true, fonts will be stored locally
    seal: true # show a title slide with YAML information
    includes:
      in_header: "assets/mathjax-equation-numbers.html"
    nature:
      beforeInit: ["assets/remark-zoom.js", "https://platform.twitter.com/widgets.js"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9' # alternatives '16:9' or '4:3' or others e.g. 13:9
      navigation:
        scroll: false # disable slide transitions by scrolling

---

background-image: url(https://upload.wikimedia.org/wikipedia/en/6/6a/Logo_of_the_University_of_Sydney.svg)
background-size: 95%

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      dev = 'svg', out.width = "45%", fig.width = 6,
                      fig.align="center")

```

---

## Acknowledgement of Country

I would like to acknowledge the Traditional Owners of Australia and  recognise their continuing connection to land, water and culture. The  University of Sydney is located on the land of the Gadigal people  of the Eora Nation. I pay my respects to their Elders, past and present.


---


## Course outline

.pull-left[

**Week 1**: Introduction

**PART I PRELIMINARY CONSIDERATIONS (Weeks 2-5)**

**Week 2**: The Selection of a Research Approach

**Week 3**: Review of the Literature

**Week 4**: The Use of Theory

**Week 5**: Writing Strategies and Ethical Considerations + Guest lecture w/t Christopher Pepin-Neff 

**PART II DESIGNING RESEARCH (Weeks 6-12)**

**Week 6**: The Introduction **no seminar** (public holiday)

⏸️ *Mid Semester break* ⏸️

]

.pull-right[


**Week 7**: The Purpose Statement 

**Week 8**: Research Questions and Hypotheses + Guest Lecture w/t Charles Robert Butcher 👈

**Week 9**: Quantitative Methods

**Week 10**: Quantitative Methods: Data Analysis Lab (Make sure you install R and RStudio)

**Week 11**: Qualitative Methods + Guest lecture w/t Peter Chen

**Week 12**: Mixed Methods Procedures + Guest lecture w/t Assel Mussagulova

**Week 13**: Conclusions


]

---

## Today's class


---

class: inverse, center, middle

# Chapter 7

# Research Questions and Hypotheses

.center[Slides adapted from Creswell, Research Design 6e, SAGE Publishing, 2023 for GOVT6139 Research Design.

Do not reshare]

---

# Chapter 7 Learning Objectives

1. Identify the types of research questions and hypotheses used in a quantitative study.

2. Learn how to write a good qualitative central question and sub-question.

3. Describe how to craft a mixed methods question describing the intent and procedures for a mixed methods study.

---

# Introduction

* Placing signposts for the reader
  * Purpose statement
  * Research questions or hypotheses
* Research questions narrow the purpose statement
  * Quantitative research questions and hypotheses
  * Qualitative research questions
  * Mixed methods research questions

---

# Quantitative Research Questions and Hypotheses (1 of 8)

* Quantitative research questions
  * About the relationships among variables that the investigator seeks to know
* Quantitative hypotheses
  * Predictions about the expected relationships among variables
  * Estimates of population values based on data from a sample

---

* Quantitative objectives
  * Indicate a study's goals
  * Often in proposals for funding, less common in health and social sciences

---

Quantitative research question describing outcomes:

What is the frequency and variation of scores on ____________ (name the variable) for ______________(participants) in the study?

---

Quantitative research question focused on examining the relationship among variables:

_________ (name the theory) posits that _____ (explain relationships between variables). It is thus predicted that there will be a relationship between ________ (predictor variable) and ________ (outcome variable), such that (explain the direction of the effect between the predictor and outcome variable).

---

Quantitative null hypothesis:

There is no significant difference between _________ (the control and experimental groups on the independent variable) on _________ (dependent variable).

---

* Three basic approaches
  * Compare groups
  * Relate variables
  * Describe responses
* Most rigorous form tests a theory
* Measure the independent and dependent variables separately
* Write questions or hypotheses
* Null and alternative hypotheses

---

* The use of variables in research questions or hypothesis if one wants to do
  * An experiment or group comparisons
  * A survey that correlates variables
  * A descriptive study

---

* If writing hypotheses, use a consistent form
  * Null hypotheses (predict no difference or no relationship)
  * Alternative hypothesis (predict significant relationship between variables)
  * Use directional words of quantitative research:
    * Affect, influence, predict, impact, determine, cause, and relate

---

# Qualitative Research Questions (1 of 6)

* Qualitative researchers pose research questions
  * Not objectives
  * Not hypotheses
* Two forms of qualitative research questions
  * Central question
    * Broad question that asks for exploration of the central phenomenon
  * Sub-questions
    * Questions that narrow the focus of the study

---

* Ask 1–2 central research questions
  * Broad and ask for exploration of the central phenomenon or concept
  * Explore the general, complex factors about to the central phenomenon
  * Present broad perspectives or meanings

---

* No more than 5–7 sub-questions these will narrow the focus but leave open the questioning
* Relate the central question to the strategy of inquiry
  * Ethnography – culture sharing group, questions verify accuracy of data
  * Critical ethnography – build on an existing literature
  * Phenomenology – what participants experienced
  * Grounded theory – generate a theory

---

Begin with “what” or “how” to convey an open or emerging design

Focus on a single phenomenon or concept

Use exploratory verbs: report, describe, discover, seek, explore, describe

---

Expect questions to evolve and change

Use open-ended questions without reference to the literature or theory (unless indicated)

Specify the participants and research site

---

_________ (How or what?) is the _________ (central phenomenon) for _________ (participants) at _________ (research site).

---

# Mixed Methods Research Questions and Hypotheses (1 of 3)

Include qualitative, quantitative (or hypotheses), and a mixed methods research question

Qualitative and quantitative questions focus the purpose

Mixed methods question conveys the importance of integrating

Use guidelines for qualitative and quantitative questions and hypotheses

---

* Order questions to match the mixed methods design
  * In a single-phase design, either first
  * In a two-phase design, order to match the phases
  * In three-phase, often mixed methods in the middle

---

A  __mixed methods research question __ directly addresses integration

Mixed methods question:

The mixed methods question in the study purpose or  _intent _ will be to ________ (compare, explain, build, augment) the ________ (quantitative data or qualitative data or process/framework) with ________ (quantitative data or qualitative data) by using a ________ (design: convergent design, explanatory sequential design, exploratory sequential design, embedded design) with the  _procedure _ of ________ (merging, connecting, or embedding).

---

# Summary

Research questions and hypotheses narrow the purpose statement and add signposts

Qualitative – central question and sub-questions

Quantitative – describe, related, compare variables

Mixed methods – qualitative, quantitative, and mixed methods question

---
